Transform: AWS::Serverless-2016-10-31
Description: Function to set INTELLIGENT_TIERING on S3 buckets.
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: s3SetIntelligentTiering.s3SetIntelligentTiering
      Runtime: python3.6
      CodeUri: ./
      Timeout: 600
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - s3:GetLifecycleConfiguration
                - s3:PutLifecycleConfiguration
                - s3:ListBucket
                - s3:ListAllMyBuckets
                - s3:GetBucketVersioning
                - s3:GetBucketPolicy
              Resource:
                - "*"
      Environment:
        Variables:
          DAYS: 30
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 ? * * *)
